//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "sys_user")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    pub name: String,
    pub id: String,
    pub gender: String,
    pub account: Option<String>,
    pub password: Option<String>,
    pub mobile_phone: Option<String>,
    pub birthday: Option<Date>,
    pub enabled: Option<bool>,
    pub created_at: Option<Time>,
    pub updated_at: Option<Time>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
